<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html" language="java" %>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://java.sun.com/jsf/ri/sandbox" prefix="risb" %>
<html>
<head>
    <title>JSF RI Sandbox  Test App</title>
    <link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
    <div class="header_main">
        <div class="header_left">JSF RI Sandbox Test App - JSP</div>
        <div class="header_right"></div>
        <div style="clear: both" />
    </div>
    </div>
    <div class="header_menu">
        <div class="header_menu_item">
            <a href="..">Home</a>
        </div>
    </div>
    <div style="margin: 5px;">