/*
 * $Id: FacesREParserConstants.java,v 1.1 2003/08/13 18:10:50 rlubke Exp $
 */

/*
 * Copyright 2003 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/* Generated By:JavaCC: Do not edit this line. FacesREParserConstants.java */

package com.sun.faces.el.ext.parser;

public interface FacesREParserConstants {

    int EOF = 0;
    int INTEGER_LITERAL = 3;
    int STRING_LITERAL = 4;
    int BADLY_ESCAPED_STRING_LITERAL = 5;
    int DOT = 6;
    int LBRACKET = 7;
    int RBRACKET = 8;
    int IDENTIFIER = 9;
    int IMPL_OBJ_START = 10;
    int LETTER = 11;
    int DIGIT = 12;
    int ILLEGAL_CHARACTER = 13;

    int DEFAULT = 0;

    String[] tokenImage = {
        "<EOF>",
        "\"\\\"\"",
        "\"\\\'\"",
        "<INTEGER_LITERAL>",
        "<STRING_LITERAL>",
        "<BADLY_ESCAPED_STRING_LITERAL>",
        "\".\"",
        "\"[\"",
        "\"]\"",
        "<IDENTIFIER>",
        "\"#\"",
        "<LETTER>",
        "<DIGIT>",
        "<ILLEGAL_CHARACTER>",
    };

}
