<f:verbatim>
<html>
<head>
    <title>JSF RI Sandbox  Test App</title>
    <link rel="stylesheet" type="text/css" href="${request.contextPath}/style.css"/>
</head>
<body>
    <div class="header_main">
        <div class="header_left">JSF RI Sandbox Test App - JSFTemplating</div>
        <div class="header_right"></div>
        <div style="clear: both" />
    </div>
    </div>
    <div class="header_menu">
        <div class="header_menu_item">
            <a href="${request.contextPath}/index.jsf">Home</a>
        </div>
    </div>
    <div style="margin: 5px;">
</f:verbatim>