/* Generated By:JJTree: Do not edit this line. AstFloat.java */

package com.sun.faces.el.impl;

import java.math.BigDecimal;

public class AstFloat extends AbstractConstantNode
{
    protected Number number;

    public AstFloat(int id)
    {
        super(id);
    }

    public Number getFloat()
    {
        if (this.number == null)
        {
            try
            {
                this.number = new Double(this.image);
            }
            catch (ArithmeticException e0)
            {
                this.number = new BigDecimal(this.image);
            }
        }
        return this.number;
    }
    
    /** Accept the visitor. * */
    public Object jjtAccept(JsfParserVisitor visitor, Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
    /* (non-Javadoc)
     * @see com.sun.faces.el.impl.AbstractConstantNode#getConstantValue()
     */
    public Object getConstantValue()
    {
        return this.getFloat();
    }
}