/* Generated By:JJTree: Do not edit this line. AstLessThanEqual.java */

package com.sun.faces.el.impl;

public class AstLessThanEqual extends AbstractNode
{
    public AstLessThanEqual(int id)
    {
        super(id);
    }
    
    /** Accept the visitor. * */
    public Object jjtAccept(JsfParserVisitor visitor, Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
}