/* Generated By:JJTree: Do not edit this line. AstNumber.java */

package com.sun.faces.el.impl;

import java.math.BigInteger;

public class AstNumber extends AbstractConstantNode
{
    protected Number number;
    
    public AstNumber(int id)
    {
        super(id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(JsfParserVisitor visitor, Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
    
    public Number getNumber()
    {
        if (this.number == null)
		{
			//try
			//{
			//	this.number = new Integer(this.image);
			//}
			//catch (ArithmeticException e0)
			//{
				try
				{
					this.number = new Long(this.image);
				}
				catch (ArithmeticException e1)
				{
					this.number = new BigInteger(this.image);
				}
			//}
		}
		return number;
    }
    
    /* (non-Javadoc)
     * @see com.sun.faces.el.impl.AbstractConstantNode#getConstantValue()
     */
    public Object getConstantValue()
    {
        return this.getNumber();
    }
}