/* Generated By:JJTree: Do not edit this line. AstProperty.java */

package com.sun.faces.el.impl;

public class AstProperty extends AbstractNode
{
    public AstProperty(int id)
    {
        super(id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(JsfParserVisitor visitor, Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
    
    public String getName()
    {
        return this.image;
    }
}