/* Generated By:JJTree: Do not edit this line. AstString.java */

package com.sun.faces.el.impl;

public class AstString extends AbstractConstantNode
{
    protected String string;
    
    public AstString(int id)
    {
        super(id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(JsfParserVisitor visitor, Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
    
    public String getString()
	{
		if (this.string == null)
		{
			this.string = this.image.substring(1, this.image.length() - 1);
		}
		return this.string;
	}
    
    /* (non-Javadoc)
     * @see com.sun.faces.el.impl.AbstractConstantNode#getConstantValue()
     */
    public Object getConstantValue()
    {
        return this.string;
    }
}