/* Generated By:JJTree: Do not edit this line. AstText.java */

package com.sun.faces.el.impl;

public class AstText extends AbstractConstantNode
{
    public AstText(int id)
    {
        super(id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(JsfParserVisitor visitor, Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
    
    public String getText()
    {
        return this.image;
    } 
    
    /* (non-Javadoc)
     * @see com.sun.faces.el.impl.AbstractConstantNode#getConstantValue()
     */
    public Object getConstantValue()
    {
        return this.getText();
    }
}