/* Generated By:JJTree: Do not edit this line. AstTrue.java */

package com.sun.faces.el.impl;

public class AstTrue extends AbstractConstantNode
{
    public AstTrue(int id)
    {
        super(id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(final JsfParserVisitor visitor, final Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
    
    /* (non-Javadoc)
     * @see com.sun.faces.el.impl.AbstractConstantNode#getConstantValue()
     */
    public Object getConstantValue()
    {
        return Boolean.TRUE;
    }
}