/* Generated By:JJTree: Do not edit this line. AstValue.java */

package com.sun.faces.el.impl;

public class AstValue extends AbstractNode
{
    public AstValue(int id)
    {
        super(id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(final JsfParserVisitor visitor, final Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }
}