/* Generated By:JJTree: Do not edit this line. AstVariable.java */

package com.sun.faces.el.impl;

public class AstVariable extends AbstractNode
{
    public AstVariable(int id)
    {
        super(id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(final JsfParserVisitor visitor, final Object data)
            throws javax.faces.el.EvaluationException
    {
        return visitor.visit(this, data);
    }

    public String getName()
    {
        return this.image;
    }
}