/* Generated By:JJTree: Do not edit this line. JsfParserTreeConstants.java */

package com.sun.faces.el.impl;

public interface JsfParserTreeConstants
{
  public int JJTCOMPLEX = 0;
  public int JJTVOID = 1;
  public int JJTTEXT = 2;
  public int JJTCHOOSE = 3;
  public int JJTOR = 4;
  public int JJTAND = 5;
  public int JJTEQUAL = 6;
  public int JJTNOTEQUAL = 7;
  public int JJTLESSTHAN = 8;
  public int JJTGREATERTHAN = 9;
  public int JJTLESSTHANEQUAL = 10;
  public int JJTGREATERTHANEQUAL = 11;
  public int JJTPLUS = 12;
  public int JJTMINUS = 13;
  public int JJTMULT = 14;
  public int JJTDIV = 15;
  public int JJTMOD = 16;
  public int JJTNEGATIVE = 17;
  public int JJTNOT = 18;
  public int JJTEMPTY = 19;
  public int JJTVALUE = 20;
  public int JJTVARIABLE = 21;
  public int JJTPROPERTY = 22;
  public int JJTPROPERTYEVAL = 23;
  public int JJTSTRING = 24;
  public int JJTNUMBER = 25;
  public int JJTFLOAT = 26;
  public int JJTTRUE = 27;
  public int JJTFALSE = 28;
  public int JJTNULL = 29;


  public String[] jjtNodeName = {
    "Complex",
    "void",
    "Text",
    "Choose",
    "Or",
    "And",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessThanEqual",
    "GreaterThanEqual",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Mod",
    "Negative",
    "Not",
    "Empty",
    "Value",
    "Variable",
    "Property",
    "PropertyEval",
    "String",
    "Number",
    "Float",
    "True",
    "False",
    "Null",
  };
}
