/* Generated By:JJTree: Do not edit this line. JsfParserVisitor.java */

package com.sun.faces.el.impl;

public interface JsfParserVisitor
{
    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstComplex node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstText node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstChoose node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstOr node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstAnd node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstEqual node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstNotEqual node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstLessThan node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstGreaterThan node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstLessThanEqual node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstGreaterThanEqual node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstPlus node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstMinus node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstMult node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstDiv node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstMod node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstNegative node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstNot node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstEmpty node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstValue node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstVariable node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstProperty node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstPropertyEval node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstString node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstNumber node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstFloat node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstTrue node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstFalse node, Object data)
            throws javax.faces.el.EvaluationException;

    /**
     * @param node
     * @param data
     * @return
     * @throws javax.faces.el.EvaluationException
     */
    public Object visit(AstNull node, Object data)
            throws javax.faces.el.EvaluationException;
}