/* Generated By:JJTree&JavaCC: Do not edit this line. JsfParserConstants.java */
package com.sun.faces.el.impl;

public interface JsfParserConstants {

  int EOF = 0;
  int NON_EXPRESSION_TEXT = 1;
  int START_EXPRESSION = 2;
  int INTEGER_LITERAL = 7;
  int FLOATING_POINT_LITERAL = 8;
  int EXPONENT = 9;
  int STRING_LITERAL = 10;
  int BADLY_ESCAPED_STRING_LITERAL = 11;
  int TRUE = 12;
  int FALSE = 13;
  int NULL = 14;
  int END_EXPRESSION = 15;
  int DOT = 16;
  int LPAREN = 17;
  int RPAREN = 18;
  int LBRACK = 19;
  int RBRACK = 20;
  int COLON = 21;
  int COMMA = 22;
  int GT0 = 23;
  int GT1 = 24;
  int LT0 = 25;
  int LT1 = 26;
  int GE0 = 27;
  int GE1 = 28;
  int LE0 = 29;
  int LE1 = 30;
  int EQ0 = 31;
  int EQ1 = 32;
  int NE0 = 33;
  int NE1 = 34;
  int NOT0 = 35;
  int NOT1 = 36;
  int AND0 = 37;
  int AND1 = 38;
  int OR0 = 39;
  int OR1 = 40;
  int EMPTY = 41;
  int INSTANCEOF = 42;
  int MULT = 43;
  int PLUS = 44;
  int MINUS = 45;
  int QUESTIONMARK = 46;
  int DIV = 47;
  int MOD0 = 48;
  int MOD1 = 49;
  int IDENTIFIER = 50;
  int IMPL_OBJ_START = 51;
  int LETTER = 52;
  int DIGIT = 53;
  int ILLEGAL_CHARACTER = 54;

  int DEFAULT = 0;
  int IN_EXPRESSION = 1;

  String[] tokenImage = {
    "<EOF>",
    "<NON_EXPRESSION_TEXT>",
    "\"#{\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<BADLY_ESCAPED_STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"}\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\">\"",
    "\"gt\"",
    "\"<\"",
    "\"lt\"",
    "\">=\"",
    "\"ge\"",
    "\"<=\"",
    "\"le\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"ne\"",
    "\"!\"",
    "\"not\"",
    "\"&&\"",
    "\"and\"",
    "\"||\"",
    "\"or\"",
    "\"empty\"",
    "\"instanceof\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"?\"",
    "\"/\"",
    "\"%\"",
    "\"mod\"",
    "<IDENTIFIER>",
    "\"#\"",
    "<LETTER>",
    "<DIGIT>",
    "<ILLEGAL_CHARACTER>",
  };

}
