/*
 * $Id: MessageResourcesFactory.java,v 1.1 2002/06/14 00:00:50 craigmcc Exp $
 */

/*
 * Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package javax.faces.context;


import java.util.Iterator;
import javax.faces.FacesException;


/**
 * <p><strong>MessageResourcesFactory</strong> is a Factory object that creates
 * (if necessary) and returns {@link MessageResources} instances.
 * Each {@link MessageResources} instance is identified by a unique
 * <code>messageResourcesId</code> identifier.  Implementations of
 * JavaServer Faces MUST return {@link MessageResources} instances for the
 * following standard message resources identifiers:</p>
 * <ul>
 * <li><strong>MessageResourcesFactory.FACES_API_MESSAGES</strong> - Messages
 *     whose message identifiers are defined in the JavaServer Faces
 *     specification, for messages generated by <code>javax.faces.*</code>
 *     concrete classes.</li>
 * <li><strong>MessageResourcesFactory.FACES_IMPL_MESSAGES</strong> - Messages
 *     whose message identifiers are defined by the JavaServer Faces
 *     implementation being utilized.</li>
 * </ul>
 *
 * <p>Additional {@link MessageResources} implementations can be registered
 * at any time, via a call to <code>addMessageResources()</code>, by
 * the application, by the JavaServer Faces implementation, or by component
 * libraries and/or <code>RenderKit</code>s utilized by the application.</p>
 *
 * <p>There shall be one <code>MessageResourcesFactory</code> instance per
 * web application that is utilizing JavaServer Faces.  This instance can be
 * acquired, in a portable manner, by calling:</p>
 * <pre>
 *   MessageResourcesFactory factory = (MessageResourcesFactory)
 *    FactoryFinder.getFactory(FactoryFinder.MESSAGE_RESOURCES_FACTORY);
 * </pre>
 */

public abstract class MessageResourcesFactory {


    // ----------------------------------------------------- Manifest Constants


    /**
     * <p>Message resources identifier for a {@link MessageResources} instance
     * containing messages whose message identifiers are defined in the
     * JavaServer Faces specification.</p>
     */
    public static final String FACES_API_MESSAGES =
        "javax.faces.context.FACES_API_MESSAGES";


    /**
     * <p>Message resources identifier for a {@link MessageResources} instance
     * containing messages whose message identifiers are defined by the
     * JavaServer Faces implementation being used.</p>
     */
    public static final String FACES_IMPL_MESSAGES =
        "javax.faces.context.FACES_IMPL_MESSAGES";


    // --------------------------------------------------------- Public Methods


    /**
     * <p>Register a new {@link MessageResources} instance, associated with
     * the specified <code>messageResourcesId</code>, to be supported by this
     * <code>MessageResourcesFactory</code>.  This method may be called at
     * any time, and makes the corresponding {@link MessageResources} instance
     * available throughout the remaining lifetime of this web application.
     * </p>
     *
     * @param messageResourcesId Message resources identifier under which
     *  the new {@link MessageResources} instance should be registered
     * @param messageResources The {@link MessageResources} instance that
     *  is being registered
     *
     * @exception IllegalArgumentException if <code>messageResourcesId</code>
     *  is already registered in this <code>MessageResourcesFactory</code>
     * @exception NullPointerException if <code>messageResourcesId</code>
     *  or <code>messageResources</code> is <code>null</code>
     */
    public abstract void addMessageResources
        (String messageResourcesId, MessageResources messageResources);


    /**
     * <p>Create (if necessary) and return a {@link MessageResources}
     * instance for the specified message resources identifier.  All requests
     * for the same message resources identifier, from the same web
     * application, must return the same {@link MessageResources} instance.
     * </p>
     *
     * @param messageResourcesId Identifier of the {@link MessageResources}
     *  instance to be returned
     *
     * @exception FacesException if the requested {@link MessageResources}
     *  instance cannot be created for some reason
     * @exception IllegalArgumentException if the specified
     *  <code>messageResourcesId</code> is not supported by this
     *  <code>MessageResourcesFactory</code>
     * @exception NullPointerException if <code>messageResourcesId</code>
     *  is <code>null</code>
     */
    public abstract MessageResources getMessageResources
        (String messageResourcesId) throws FacesException;


    /**
     * <p>Return an <code>Iterator</code> over the set of message resource
     * identifiers supported by this factory.  This <code>Iterator</code>
     * MUST include the standard identifiers described above.</p>
     */
    public abstract Iterator getMessageResourcesIds();


}
