/*
 * $Id: FacesEvent.java,v 1.8 2002/04/05 19:40:16 jvisvanathan Exp $
 */

/*
 * Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package javax.faces;

import java.util.EventObject;
import javax.servlet.ServletRequest;

/**
 * The base-class for JavaServer Faces fc objects which
 * are generated by user-interface components.  An Event object
 * encapsulates any state associated with a particular event.
 */
public abstract class FacesEvent extends EventObject {
    private UIComponent sourceComponent = null;
    private FacesContext facesContext;

    /**
     * Initializes the facesContext and sourceName properties of
     * this FacesEvent object.
     * @param fc FacesContext object representing the event-processing 
     *           phase of the request where this event originated
     * @param sourceComponent the component where this event originated
     * @throws NullPointerException if sourceName is null
     */
    protected FacesEvent(FacesContext fc, UIComponent sourceComponent) {
	super(sourceComponent);
	this.facesContext = fc;
	this.sourceComponent = sourceComponent;
    }

    /**
     * @return FacesContext object representing the event-processing 
     *           phase of the request where this event originated
     */
    public FacesContext getFacesContext() {
	return facesContext;
    }

    /**
     * @return object where this event originated
     */
    public Object getSource() {
	return getSourceComponent();
    }

    /**
     * This is a convenience method for <code>getSource</code> which
     * returns the source object cast to UIComponent.
     * @return UIComponent where this event originated
     */
    public UIComponent getSourceComponent() {
        return sourceComponent;
    }
}
