/*
 * $Id: FacesEvent.java,v 1.7 2002/03/07 23:44:03 eburns Exp $
 */

/*
 * Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package javax.faces;

import java.util.EventObject;
import javax.servlet.ServletRequest;

/**
 * The base-class for JavaServer Faces event objects which
 * are generated by user-interface components.  An Event object
 * encapsulates any state associated with a particular event.
 */
public abstract class FacesEvent extends EventObject {
    private UIComponent sourceComponent = null;
    private EventContext eventContext;

    /**
     * Initializes the eventContext and sourceName properties of
     * this FacesEvent object.
     * @param ec EventContext object representing the event-processing 
     *           phase of the request where this event originated
     * @param sourceComponent the component where this event originated
     * @throws NullPointerException if sourceName is null
     */
    protected FacesEvent(EventContext ec, UIComponent sourceComponent) {
	super(sourceComponent);
	this.eventContext = ec;
	this.sourceComponent = sourceComponent;
    }

    /**
     * @return EventContext object representing the event-processing 
     *           phase of the request where this event originated
     */
    public EventContext getEventContext() {
	return eventContext;
    }

    /**
     * @return object where this event originated
     */
    public Object getSource() {
	return getSourceComponent();
    }

    /**
     * This is a convenience method for <code>getSource</code> which
     * returns the source object cast to UIComponent.
     * @return UIComponent where this event originated
     */
    public UIComponent getSourceComponent() {
        return sourceComponent;
    }
}
